# =================================================================
# AZURE PIPELINE PARA "CENTAVO" (DJANGO) - VERSIÓN DE ZIP DEPLOY
# Versión: 2.1 (Final)
# Última corrección: Simplificar el nombre del artefacto a 'app.zip'.
# =================================================================

trigger:
- main

variables:
  azureSubscription: 'Azure-Subscription-Connection'
  appName: 'app-centavo'
  resourceGroup: 'rg-centavo'
  vmImageName: 'ubuntu-latest'
  pythonVersion: '3.11'

stages:
- stage: Build
  displayName: 'Build and Package'
  jobs:
  - job: BuildJob
    pool:
      vmImage: $(vmImageName)
    steps:
    # Este paso toma todo el código fuente y lo comprime en un archivo .zip.
    - task: ArchiveFiles@2
      displayName: 'Archive source code'
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        # CORRECCIÓN: Usamos un nombre de archivo estático y predecible.
        archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
        replaceExistingArchive: true

    # Este paso toma el archivo .zip generado y lo "publica"
    # como un artefacto oficial de esta construcción del pipeline.
    - task: PublishBuildArtifacts@1
      displayName: 'Publish artifact for deployment'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy to Azure'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: DeployJob
    pool:
      vmImage: $(vmImageName)
    steps:
    # Este paso despliega el .zip. Azure se encargará de descomprimirlo
    # y ejecutar el sistema de construcción Oryx para instalar dependencias.
    - task: AzureWebApp@1
      displayName: 'Deploy to Azure App Service'
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(appName)
        resourceGroupName: $(resourceGroup)
        # CORRECCIÓN: La ruta ahora apunta al nombre de archivo estático.
        package: '$(Pipeline.Workspace)/drop/app.zip'