# =================================================================
# AZURE PIPELINE PARA "CENTAVO" (DJANGO) - VERSIÓN DE ZIP DEPLOY
# Versión: 2.2 (Final y Correcta)
# Última corrección: Añadir explícitamente la descarga de artefactos.
# =================================================================

trigger:
- main

variables:
  azureSubscription: 'Azure-Subscription-Connection'
  appName: 'app-centavo'
  resourceGroup: 'rg-centavo'
  vmImageName: 'ubuntu-latest'
  pythonVersion: '3.11'

stages:
- stage: Build
  displayName: 'Build and Package'
  jobs:
  - job: BuildJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: ArchiveFiles@2
      displayName: 'Archive source code'
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish artifact for deployment'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy to Azure'
  dependsOn: Build
  condition: succeeded()
  jobs:
  # --- INICIO DE LA CORRECCIÓN ---
  # El deployment job es un tipo especial que necesita ser definido así.
  - deployment: DeployJob
    displayName: Deploy App Service
    environment: 'production' # Puedes nombrar el entorno como quieras
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          # PASO 1: Descargar el artefacto del stage anterior
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(Pipeline.Workspace)'

          # PASO 2: Desplegar el .zip descargado
          - task: AzureWebApp@1
            displayName: 'Deploy to Azure App Service'
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(appName)
              resourceGroupName: $(resourceGroup)
              package: '$(Pipeline.Workspace)/drop/app.zip'
  # --- FIN DE LA CORRECCIÓN ---