# Generated by Django 5.2.6 on 2025-09-23 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_recipeingredient'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_produced', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Producida')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Total de Producción')),
                ('production_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Producción')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_logs', to='products.product', verbose_name='Producto Terminado')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_logs', to='tenants.tenant', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Registro de Producción',
                'verbose_name_plural': 'Registros de Producción',
                'ordering': ['-production_date'],
            },
        ),
    ]
