# Generated by Django 5.2.6 on 2025-09-21 19:51

from django.db import migrations, models


# --- Función para inicializar quantity_remaining ---
def set_quantity_remaining_initial(apps, schema_editor):
    PurchaseBatch = apps.get_model('inventory', 'PurchaseBatch')
    for batch in PurchaseBatch.objects.all():
        batch.quantity_remaining = batch.quantity
        batch.save(update_fields=['quantity_remaining'])
# --- Fin de la función ---

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebatch',
            name='quantity_remaining',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cantidad Restante'),
        ),
        # --- AÑADE ESTA OPERACIÓN RUNPYTHON ---
        migrations.RunPython(set_quantity_remaining_initial, migrations.RunPython.noop),
        # --- FIN OPERACIÓN RUNPYTHON ---
    ]
