"""
Django settings for centavo project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ==============================================================================
# CONFIGURACIÓN DE SEGURIDAD Y ENTORNO
# ==============================================================================

# Lee la SECRET_KEY de las variables de entorno. CRÍTICO para producción.
SECRET_KEY = config('DJANGO_SECRET_KEY')

# Lee el modo DEBUG de las variables de entorno. Será 'False' en Azure.
DEBUG = config('DEBUG', default=False, cast=bool)

# Define en qué dominios puede ejecutarse la aplicación en producción.
ALLOWED_HOSTS = ['app-centavo.azurewebsites.net']

# Añade hosts de desarrollo local solo si DEBUG es True.
if DEBUG:
    ALLOWED_HOSTS.append('localhost')
    ALLOWED_HOSTS.append('127.0.0.1')


# ==============================================================================
# DEFINICIÓN DE APLICACIONES
# ==============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_vite',

    # Apps de Terceros
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_extensions',

    # Nuestras Apps
    'users.apps.UsersConfig',
    'tenants.apps.TenantsConfig',
    'inventory.apps.InventoryConfig',
    'products.apps.ProductsConfig',
    'production.apps.ProductionConfig',
    'finance.apps.FinanceConfig',
]

# Añade 'whitenoise.runserver_nostatic' solo en modo de depuración para desarrollo.
if DEBUG:
    INSTALLED_APPS.append('whitenoise.runserver_nostatic')

AUTH_USER_MODEL = 'users.User'


# ==============================================================================
# CONFIGURACIÓN DE MIDDLEWARE
# ==============================================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise Middleware debe ir justo después de SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ==============================================================================
# CONFIGURACIÓN DE RUTAS Y PLANTILLAS
# ==============================================================================

ROOT_URLCONF = 'centavo.urls'
WSGI_APPLICATION = 'centavo.wsgi.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ==============================================================================
# CONFIGURACIÓN DE LA BASE DE DATOS
# ==============================================================================

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        ssl_require=True
    )
}


# ==============================================================================
# CONFIGURACIÓN DE ARCHIVOS ESTÁTICOS Y DE MEDIOS (PRODUCCIÓN)
# ==============================================================================

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Directorios para buscar estáticos durante el desarrollo.
STATICFILES_DIRS = [
    BASE_DIR / "frontend" / "dist",
]

# SOLUCIÓN FINAL: En producción, confiamos únicamente en STATIC_ROOT
# después de que `collectstatic` se ha ejecutado en el pipeline.
if not DEBUG:
    STATICFILES_DIRS = []

# Almacenamiento optimizado para WhiteNoise en producción.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ==============================================================================
# CONFIGURACIONES DE APPS DE TERCEROS (REST FRAMEWORK, JWT, CORS, VITE)
# ==============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 6
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

# Orígenes permitidos para peticiones CORS (solo para desarrollo).
# En producción, esto debería ser más restrictivo.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

VITE_APP_DIR = BASE_DIR / "frontend"
DJANGO_VITE = {
    "default": {
        "dev_mode": DEBUG,
        "dev_server_host": "localhost",
        "dev_server_port": 5173,
        "manifest_path": VITE_APP_DIR / "dist" / "manifest.json",
    }
}


# ==============================================================================
# OTRAS CONFIGURACIONES DE DJANGO
# ==============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'es-ni'
TIME_ZONE = 'America/Managua'
USE_I18N = True
USE_L10N = True
USE_TZ = True
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'