# Generated by Django 5.2.6 on 2025-09-21 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Categoría')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de Venta Sugerido')),
                ('stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Stock Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Producto Terminado',
                'verbose_name_plural': 'Productos Terminados',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
    ]
